### ISSUE TITLE
port is not generated and exposeService becomes = false

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#313] opened 2019-08-19 15:54 UTC
## Issue

port is not generated and exposeService becomes = false even if we define within the java class this annotation

```
import io.dekorate.halkyon.annotation.HalkyonComponent;
import io.dekorate.halkyon.annotation.HalkyonLink;
import io.dekorate.halkyon.model.Kind;
import io.dekorate.kubernetes.annotation.Env;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Entry point to the application.
 */
@SpringBootApplication
@HalkyonComponent(
    name = "fruit-client-sb",
    exposeService = true
)
@HalkyonLink(
    name = "link-to-fruit-backend",
    componentName = "fruit-client-sb",
    kind = Kind.Env,
    envs = @Env(
        name = "ENDPOINT_BACKEND",
        value = "http://fruit-backend-sb:8080/api/fruits"
    )
)
```

and server port under the application.yml file
```
server:
  port: 8080

# Endpoint property to access the backend microservice
endpoint:
  fruit: ${ENDPOINT_BACKEND}

# Halkyon properties to configure the component, link or capability
dekorate:
  component:
    deploymentMode: build
```

Generated
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "fruit-client-sb"
    name: "fruit-client-sb"
  spec:
    deploymentMode: "build"
    runtime: "spring-boot"
    version: "2.1.6.RELEASE"
    exposeService: false
    buildConfig:
      type: "s2i"
      url: "git+ssh://git@github.com/halkyonio/operator"
      ref: "master"
      contextPath: "demo/"
      moduleDirName: "fruit-client-sb"
- apiVersion: "halkyon.io/v1beta1"
  kind: "Link"
  metadata:
    name: "link-to-fruit-backend"
  spec:
    componentName: "fruit-client-sb"
    kind: "Env"
    ref: ""
    envs:
    - name: "ENDPOINT_BACKEND"
      value: "http://fruit-backend-sb:8080/api/fruits"
```

See project: https://github.com/halkyonio/operator/blob/master/demo/fruit-client-sb/src/main/resources/application.yml#L2

**Comment by cmoulliard** [comment] 2019-08-19 16:07
The problem can be resolved if we add `    exposeService: true` to the application.yml file

**Comment by geoand** [comment] 2019-08-21 09:02
I haven't followed the latest discussions on the design of annotation-less mode, so I am not sure if this behavior is expected or not.

What I am observing, is that when one mixes Dekorate properties and annotations, all the "configuration" from annotations is lost.

In this super simple example:

```
@HalkyonComponent(exposeService = true, name = "my-example")
@SpringBootApplication
public class Main {

  public static void main(String[] args) {
    SpringApplication.run(Main.class, args);
  }

}
```

when `application.yaml` contains only:

```
server:
    port: 9090
```

then the result is:

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "my-example"
    name: "my-example"
  spec:
    deploymentMode: "dev"
    runtime: "spring-boot"
    version: "2.1.0.RELEASE"
    exposeService: true
    port: 9090
```

In this example all the dekorate "configuration" is taken from the annotation.

However if I change `application.yaml` to:

```
server:
    port: 9090

dekorate:
    component:
        deploymentMode: build
```

then the result is:

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "halkyon.io/v1beta1"
  kind: "Component"
  metadata:
    labels:
      app: "halkyon-example"
    name: "halkyon-example"
  spec:
    deploymentMode: "build"
    runtime: "spring-boot"
    version: "2.1.0.RELEASE"
    exposeService: false
    buildConfig:
      type: "s2i"
      url: "https://github.com/dekorateio/dekorate.git"
      ref: "master"
      contextPath: "examples/"
      moduleDirName: "halkyon-example"
```

which to me suggest that annotations are not considered at all because we supplied some dekorate "configuration" via `application.properties`.
Like I said, I am not sure if this is by design or not. @aureamunoz @metacosm WDYT?

Note: I tested all the above from `master`

**Comment by geoand** [comment] 2019-08-21 10:26
[This](https://github.com/dekorateio/dekorate/pull/312#discussion_r316074599) comment seems to provide clarity of the behavior.
So I guess this is not a bug, but the expected behavior

**Comment by aureamunoz** [comment] 2019-08-21 10:32
Yes, in the current state of things, the `application.properties/yml` take precedence over the annotation configured values so such values are override by values in the provided file.

**Comment by geoand** [comment] 2019-08-21 10:34
Just to be clear, annotations and yaml/properties don't get "merged", do they?
I mean using some configuration from one and some from the other doesn't result in both being added, but only the configuration from the properties/yaml, correct?

**Comment by metacosm** [comment] 2019-08-21 10:58
Yes, I think so and I will clarify this in the doc. We might want to implement a merge behavior at some point if possible…

**Comment by geoand** [comment] 2019-08-21 10:59
Who is doing the docs update, you @metacosm or @aureamunoz ? Should we just update the docs and close this issue for now?

Merging the two different strategies would be interesting, but probably not without issues :)

**Comment by aureamunoz** [comment] 2019-08-21 11:03
Yes, it would be interesting 
I have done some updates but right now @metacosm is working on doc, @geoand

**Comment by geoand** [comment] 2019-08-21 11:07
OK, thanks for the updates!

I think it's very important to clarify this point since it's very easy to get confused

**Comment by metacosm** [comment] 2019-08-21 11:43
Agreed.

**Comment by metacosm** [comment] 2019-08-21 15:01
The documentation should now be clearer on this aspect.

**Closed by metacosm** 2019-08-21 15:01 UTC
Labels: bug
