### ISSUE TITLE
gradle/kotlin dsl + springboot :: Unable to generate the manifest

### ISSUE THREAD

**Issue by fladulima** [dekorateio/dekorate#405] opened 2019-11-15 19:05 UTC
The combination SpringBoot and gradle with kotlin dsl does not work.  
It happened during compileJava task. 
Not sure if I'm missing any configuration. 

This is part of the stacktrace: 

```
Caused by: java.io.UncheckedIOException: java.io.IOException: Is a directory
        at io.dekorate.project.BazelInfoReader.readBuild(BazelInfoReader.java:107)
        at io.dekorate.project.BazelInfoReader.getInfo(BazelInfoReader.java:69)
        at io.dekorate.project.FileProjectFactory.lambda$getProjectInfo$2(FileProjectFactory.java:79)
        at io.dekorate.project.FileProjectFactory.getProjectInfo(FileProjectFactory.java:79)
        at io.dekorate.project.FileProjectFactory.createInternal(FileProjectFactory.java:54)
        at io.dekorate.project.FileProjectFactory.create(FileProjectFactory.java:43)
        at io.dekorate.project.AptProjectFactory.createInternal(AptProjectFactory.java:50)
        at io.dekorate.project.AptProjectFactory.create(AptProjectFactory.java:40)
        at io.dekorate.processor.AbstractAnnotationProcessor.init(AbstractAnnotationProcessor.java:68)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
        at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.init(NonIncrementalProcessor.java:33)
```

Here's the sample project:
https://github.com/fladulima/dekorate-poc.git

Thanks

**Comment by iocanel** [comment] 2019-11-22 16:59
@fladulima: should I assume that the issue is now fixed  (after your pull request)?

**Comment by fladulima** [comment] 2019-11-22 17:10
Yes, you may close it.
Thanks.

**Closed** 2019-11-22 17:10 UTC
